import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {PGlite} from '@electric-sql/pglite';
import {readDatabase,visibleState} from './data.js';import {buildOperations} from './operations.js';import {login,identity,sameOrigin} from './auth.js';
const actor={role:'SUPERVISOR',user:'EDUARDO'},admin={role:'CONTROLADORIA',user:'CONTROLADORIA'},finance={role:'FINANCEIRO',user:'FINANCEIRO'},now='2026-10-08T12:00:00Z';
function driver(pg){const sql=(strings,...values)=>{const text=strings.reduce((t,s,i)=>t+(i?'$'+i:'')+s,'');return {text,values,then(a,b){return pg.query(text,values).then(r=>r.rows).then(a,b);}};};sql.transaction=queries=>pg.transaction(async tx=>{const result=[];for(const q of queries)result.push((await tx.query(q.text,q.values)).rows);return result;});return sql;}
async function fixture(){const pg=new PGlite();await pg.exec(fs.readFileSync(new URL('./fixture-schema.sql',import.meta.url),'utf8'));await pg.exec(fs.readFileSync(new URL('../migracao_homologacao.sql',import.meta.url),'utf8'));await pg.exec("INSERT INTO colaboradores(nome,funcao,valor_diaria) VALUES('Pessoa QA','Eletricista',241.74); INSERT INTO obras(unidade,nome) VALUES('FIEC','Serviço 1'),('FIEC','Serviço 2'),('SEBRAE','Serviço noturno');");return {pg,sql:driver(pg)};}
async function save(sql,next,session,version){const before=await readDatabase(sql),ops=buildOperations(before,next,session,now);const rid=crypto.randomUUID();await sql`SELECT aproar_web_apply(${version||before.version},${rid},${session.user},${'digest'},${JSON.stringify(ops)}::jsonb)`;return {after:await readDatabase(sql),rid,ops};}
function conv(state){state.convocacoes.push({id:'draft-conv',supervisor:'EDUARDO',dataServico:'2026-10-07',unidade:'FIEC',obraId:'',turno:'Integral',colaboradores:['1']});}
function attendance(state,id){state.apontamentos.push({id:'draft-ap',convocacaoId:id,supervisor:'EDUARDO',dataServico:'2026-10-07',retroativo:true,itens:[{colaboradorId:'1',status:'Presente (Integral)',extra:'Meia diária',financeiro:120,noturno:0,acordo:20,observacao:'Teste',servicos:[{obraId:'1',periodo:'Manhã'},{obraId:'2',periodo:'Tarde'}]}]});}
test('Atomic creation, multiple services, exact costs and dual-write compatibility',async()=>{const {pg,sql}=await fixture();try{const initial=await readDatabase(sql),next=structuredClone(initial.state);conv(next);attendance(next,'draft-conv');const {after,ops}=await save(sql,next,actor);assert.equal(after.state.convocacoes.length,1);assert.equal(after.state.apontamentos.length,1);assert.equal(after.raw.servicos_apontamento.length,2);assert.equal(Number(after.raw.apontamentos[0].valor_extra),120.87);assert.equal(Number(after.raw.apontamentos[0].custo_encargos_base),362.61);assert.equal(after.raw.apontamentos[0].tipo_diaria,'Meia diária');assert.equal(Number(after.raw.convocacoes[0].custo_pago),120);assert.equal(after.state.apontamentos[0].executor,'EDUARDO');assert(!ops.some(o=>o.table==='colaboradores'));assert.notEqual(initial.version,after.version);}finally{await pg.close();}});
test('Stale write rolls back all operations',async()=>{const {pg,sql}=await fixture();try{const initial=await readDatabase(sql),next=structuredClone(initial.state);conv(next);await pg.exec("UPDATE colaboradores SET nome='Alterado no Streamlit' WHERE id=1");const ops=buildOperations(initial,next,actor,now);await assert.rejects(async()=>await sql`SELECT aproar_web_apply(${initial.version},${crypto.randomUUID()},${actor.user},${'hash'},${JSON.stringify(ops)}::jsonb)`,/APROAR_STALE/);assert.equal((await pg.query('SELECT count(*)::int n FROM convocacoes')).rows[0].n,0);}finally{await pg.close();}});
test('Invalid statement after a valid insert rolls back the entire transaction',async()=>{const {pg,sql}=await fixture();try{const db=await readDatabase(sql),ops=[{table:'obras',action:'insert',id:'temp',data:{nome:'New',unidade:'FIEC'}},{table:'obras',action:'insert',id:'bad',data:{nome:null,unidade:'FIEC'}}];await assert.rejects(async()=>await sql`SELECT aproar_web_apply(${db.version},${crypto.randomUUID()},${admin.user},${'hash'},${JSON.stringify(ops)}::jsonb)`);assert.equal((await pg.query('SELECT count(*)::int n FROM obras')).rows[0].n,3);}finally{await pg.close();}});
test('Retries of the same request cannot create duplicate convocations',async()=>{const {pg,sql}=await fixture();try{const db=await readDatabase(sql),next=structuredClone(db.state);conv(next);const ops=buildOperations(db,next,actor,now),id=crypto.randomUUID();await sql`SELECT aproar_web_apply(${db.version},${id},${actor.user},${'hash'},${JSON.stringify(ops)}::jsonb)`;await sql`SELECT aproar_web_apply(${db.version},${id},${actor.user},${'hash'},${JSON.stringify(ops)}::jsonb)`;assert.equal((await pg.query('SELECT count(*)::int n FROM convocacoes')).rows[0].n,1);}finally{await pg.close();}});
test('Supervisor cannot change another supervisor or financial protected values',async()=>{const {pg,sql}=await fixture();try{let db=await readDatabase(sql),next=structuredClone(db.state);conv(next);next.convocacoes[0].supervisor='FELIPE';assert.throws(()=>buildOperations(db,next,actor,now),/própria equipe/);next=structuredClone(db.state);conv(next);attendance(next,'draft-conv');db=(await save(sql,next,actor)).after;next=structuredClone(db.state);next.apontamentos[0].itens[0].status='Falta';assert.throws(()=>buildOperations(db,next,finance,now),/só altera pagamentos/);next=structuredClone(db.state);next.apontamentos[0].itens[0].financeiro=180;db=(await save(sql,next,finance)).after;assert.equal(Number(db.raw.apontamentos[0].custo_pago),180);assert.equal(db.raw.apontamentos[0].apontado_por,'EDUARDO');assert.equal(db.raw.apontamentos[0].custo_pago_definido_financeiro,true);assert.throws(()=>buildOperations(db,db.state,{role:'VISUALIZAR',user:'VISUALIZAR'},now),/somente visualização/);}finally{await pg.close();}});
test('Cross-unit overlapping turns are rejected while morning/evening coexist',async()=>{const {pg,sql}=await fixture();try{const db=await readDatabase(sql),next=structuredClone(db.state);conv(next);next.convocacoes[0].turno='Manhã';next.convocacoes.push({...next.convocacoes[0],id:'second',unidade:'SEBRAE',turno:'Tarde'});assert.doesNotThrow(()=>buildOperations(db,next,actor,now));next.convocacoes[1].turno='Integral';assert.throws(()=>buildOperations(db,next,actor,now),/Conflito/);}finally{await pg.close();}});
test('New temporary collaborator IDs resolve atomically with convocation and attendance',async()=>{const {pg,sql}=await fixture();try{const db=await readDatabase(sql),next=structuredClone(db.state);next.colaboradores.push({id:'temp-worker',nome:'Avulso QA',funcao:'Pedreiro',custo:241.74,moradia:'',inativo:false,categoria:'Profissional',avulso:'Sim'});conv(next);next.convocacoes[0].colaboradores=['temp-worker'];attendance(next,'draft-conv');next.apontamentos[0].itens[0].colaboradorId='temp-worker';const after=(await save(sql,next,actor)).after;assert.equal(after.state.colaboradores.length,2);assert.equal(after.state.convocacoes[0].colaboradores[0],'2');assert.equal(after.raw.apontamentos[0].colaborador_id,'2');}finally{await pg.close();}});
test('Signed sessions reject tampering, expiry, bad passwords and cross-origin writes',async()=>{const env={CONNECTION_CHECK_TOKEN:'a'.repeat(40),ADMIN_PASSWORD:'admin-qa',FINANCE_PASSWORD:'finance-qa',VIEWER_PASSWORD:'viewer-qa',SUPERVISOR_PASSWORDS:JSON.stringify({EDUARDO:'supervisor-qa'})};const result=await login({role:'SUPERVISOR',supervisor:'EDUARDO',password:'supervisor-qa'},env);const cookie=result.cookie.split(';')[0];assert.equal((await identity(new Request('https://app.test',{headers:{cookie}}),env)).user,'EDUARDO');assert.equal(await identity(new Request('https://app.test',{headers:{cookie:cookie.replace('aproar_session=','aproar_session=x')}}),env),null);await assert.rejects(login({role:'CONTROLADORIA',password:'wrong'},env),/inválidos/);assert.equal(sameOrigin(new Request('https://app.test',{headers:{origin:'https://other.test'}})),false);});

test('Corrections keep finance adjustments and attendance date consistent',async()=>{const {pg,sql}=await fixture();try{let db=await readDatabase(sql),next=structuredClone(db.state);conv(next);attendance(next,'draft-conv');db=(await save(sql,next,actor)).after;next=structuredClone(db.state);next.apontamentos[0].itens[0].financeiro=180;db=(await save(sql,next,finance)).after;next=structuredClone(db.state);next.apontamentos[0].itens[0].financeiro=1;next.apontamentos[0].itens[0].observacao='Correção supervisor';db=(await save(sql,next,actor)).after;assert.equal(Number(db.raw.apontamentos[0].custo_pago),180);next=structuredClone(db.state);next.convocacoes[0].dataServico='2026-10-06';db=(await save(sql,next,admin)).after;assert.equal(db.state.apontamentos[0].dataServico,'2026-10-06');assert.equal(new Date(db.raw.apontamentos[0].data_servico).toISOString().slice(0,10),'2026-10-06');}finally{await pg.close();}});

test('Unchanged legacy supervisor does not block a new convocation from a valid supervisor',async()=>{
 const {pg,sql}=await fixture();
 try{
  await pg.exec("INSERT INTO convocacoes(obra_id,colaborador_id,data,engenheiro,turno,observacao) VALUES(1,1,'2026-10-06','ENGENHEIRO ANTIGO','Integral','Turno: Integral')");
  const db=await readDatabase(sql),next=structuredClone(db.state);
  assert.equal(next.convocacoes[0].supervisor,'ENGENHEIRO ANTIGO');
  next.convocacoes.push({id:'new-conv-qa',supervisor:'EDUARDO',dataServico:'2026-10-07',unidade:'FIEC',obraId:'',turno:'Integral',colaboradores:['1']});
  const ops=buildOperations(db,next,actor,now);
  assert.equal(ops.filter(x=>x.table==='convocacoes'&&x.action==='insert').length,1);
  assert.equal(ops.filter(x=>x.table==='convocacoes'&&x.action==='update').length,0);
  const after=(await save(sql,next,actor)).after;
  assert.equal(after.raw.convocacoes.length,2);
  assert.equal(after.raw.convocacoes.find(x=>x.engenheiro==='ENGENHEIRO ANTIGO').engenheiro,'ENGENHEIRO ANTIGO');
 }finally{await pg.close();}
});
test('New or reassigned invalid supervisor remains forbidden',async()=>{
 const {pg,sql}=await fixture();
 try{
  const db=await readDatabase(sql),next=structuredClone(db.state);
  next.convocacoes.push({id:'bad-conv',supervisor:'ENGENHEIRO ANTIGO',dataServico:'2026-10-07',unidade:'FIEC',obraId:'',turno:'Integral',colaboradores:['1']});
  assert.throws(()=>buildOperations(db,next,actor,now),/Supervisor inválido/);
 }finally{await pg.close();}
});
